CREATE TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE (id INT, name VARCHAR(100));
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD variant_col VARIANT;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD array_col ARRAY;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD object_col OBJECT;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD geography_col GEOGRAPHY;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD "timestamp_ntz" TIMESTAMP_NTZ;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD not_null_col VARCHAR(50) NOT NULL;
ALTER TABLE LTHDB.TEST_ADDCOLUMNSNOWFLAKE.COLUMN_TEST_TABLE ADD default_col INT DEFAULT 0;