ALTER TABLE ${CATALOG_NAME}.PUBLIC.authors ADD varcharColumn VARCHAR(25)
ALTER TABLE ${CATALOG_NAME}.PUBLIC.authors ADD intColumn INT
ALTER TABLE ${CATALOG_NAME}.PUBLIC.authors ADD dateColumn date
UPDATE ${CATALOG_NAME}.PUBLIC.authors SET varcharColumn = 'INITIAL_VALUE'
UPDATE ${CATALOG_NAME}.PUBLIC.authors SET intColumn = 5
UPDATE ${CATALOG_NAME}.PUBLIC.authors SET dateColumn = '2020-09-21'