ALTER TABLE LTHDB.TESTHARNESS.authors ADD varcharColumn VARCHAR(25)
ALTER TABLE LTHDB.TESTHARNESS.authors ADD intColumn INT
ALTER TABLE LTHDB.TESTHARNESS.authors ADD dateColumn date
UPDATE LTHDB.TESTHARNESS.authors SET varcharColumn = 'INITIAL_VALUE'
UPDATE LTHDB.TESTHARNESS.authors SET intColumn = 5
UPDATE LTHDB.TESTHARNESS.authors SET dateColumn = '2020-09-21'