USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TEST_AddLookupTable CASCADE
CREATE SCHEMA TEST_AddLookupTable
USE SCHEMA TEST_AddLookupTable
GRANT ALL PRIVILEGES ON SCHEMA TEST_AddLookupTable TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
CREATE TABLE LTHDB.TEST_AddLookupTable.authors_data AS SELECT DISTINCT email AS authors_email FROM LTHDB.TEST_AddLookupTable.authors WHERE email IS NOT NULL
ALTER TABLE LTHDB.TEST_AddLookupTable.authors_data ALTER COLUMN  authors_email SET NOT NULL
ALTER TABLE LTHDB.TEST_AddLookupTable.authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE LTHDB.TEST_AddLookupTable.authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES LTHDB.TEST_AddLookupTable.authors_data (authors_email)