CREATE TABLE LTHDB.TESTHARNESS.authors_data AS SELECT DISTINCT email AS authors_email FROM LTHDB.TESTHARNESS.authors WHERE email IS NOT NULL
ALTER TABLE LTHDB.TESTHARNESS.authors_data ALTER COLUMN  authors_email SET NOT NULL
ALTER TABLE LTHDB.TESTHARNESS.authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE LTHDB.TESTHARNESS.authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES LTHDB.TESTHARNESS.authors_data (authors_email)