-- Liquibase Snowflake SQL
-- MUST include ALL SQL including init.xml
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TEST_AlterTableCluster CASCADE
CREATE SCHEMA TEST_AlterTableCluster
USE SCHEMA TEST_AlterTableCluster
GRANT ALL PRIVILEGES ON SCHEMA TEST_AlterTableCluster TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP TABLE IF EXISTS LTHDB.TEST_AlterTableCluster.TEST_TABLE_CLUSTER CASCADE
CREATE TABLE LTHDB.TEST_AlterTableCluster.TEST_TABLE_CLUSTER (
id INT,
name VARCHAR(50),
created_date DATE,
region VARCHAR(20)
)
ALTER TABLE LTHDB.TEST_AlterTableCluster.TEST_TABLE_CLUSTER CLUSTER BY (region,created_date)