CREATE TABLE LTHDB.TEST_ALTERTABLEPROPERTIES.PROP_TEST_TABLE (id INT, name VARCHAR(100));
ALTER TABLE LTHDB.TEST_ALTERTABLEPROPERTIES.PROP_TEST_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 7, CHANGE_TRACKING = TRUE, ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE LTHDB.TEST_ALTERTABLEPROPERTIES.PROP_TEST_TABLE CLUSTER BY (id);