DROP SCHEMA IF EXISTS TEST_ALTER_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_RENAME_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_RENAMED_SCHEMA CASCADE
CREATE SCHEMA IF NOT EXISTS TEST_ALTER_SCHEMA
COMMENT = 'Initial schema for alter tests'
DATA_RETENTION_TIME_IN_DAYS = 7
CREATE SCHEMA IF NOT EXISTS TEST_RENAME_SCHEMA
WITH MANAGED ACCESS
COMMENT = 'Schema to be renamed'
ALTER SCHEMA TEST_ALTER_SCHEMA SET COMMENT = 'Modified schema comment'
ALTER SCHEMA TEST_ALTER_SCHEMA SET DATA_RETENTION_TIME_IN_DAYS = 30
ALTER SCHEMA TEST_ALTER_SCHEMA ENABLE MANAGED ACCESS
ALTER SCHEMA TEST_RENAME_SCHEMA RENAME TO TEST_RENAMED_SCHEMA
ALTER SCHEMA TEST_ALTER_SCHEMA UNSET COMMENT
DROP SCHEMA TEST_ALTER_SCHEMA
DROP SCHEMA TEST_RENAMED_SCHEMA