USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TEST_AlterSequenceWithNoOrder CASCADE
CREATE SCHEMA TEST_AlterSequenceWithNoOrder
USE SCHEMA TEST_AlterSequenceWithNoOrder
GRANT ALL PRIVILEGES ON SCHEMA TEST_AlterSequenceWithNoOrder TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
CREATE SEQUENCE TEST_AlterSequenceWithNoOrder.test_alter_sequence START WITH 1 INCREMENT BY 1
ALTER SEQUENCE TEST_AlterSequenceWithNoOrder.test_alter_sequence INCREMENT BY 5