DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_ALTER
DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_RENAME
DROP WAREHOUSE IF EXISTS WAREHOUSE_RENAMED
DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_SUSPEND
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE WAREHOUSE_TO_ALTER WITH WAREHOUSE_SIZE = SMALL
CREATE WAREHOUSE WAREHOUSE_TO_RENAME WITH WAREHOUSE_SIZE = XSMALL
CREATE WAREHOUSE WAREHOUSE_TO_SUSPEND WITH WAREHOUSE_SIZE = XSMALL AUTO_RESUME = false
ALTER WAREHOUSE WAREHOUSE_TO_RENAME RENAME TO WAREHOUSE_RENAMED
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE WAREHOUSE_TO_ALTER SET WAREHOUSE_SIZE = SMALL, AUTO_SUSPEND = 300
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE WAREHOUSE_TO_ALTER SET MAX_CLUSTER_COUNT = 3, MIN_CLUSTER_COUNT = 1, SCALING_POLICY = STANDARD
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE IF EXISTS WAREHOUSE_TO_ALTER SET COMMENT = 'Updated warehouse', ENABLE_QUERY_ACCELERATION = true, QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8
USE WAREHOUSE LTHDB_TEST_WH
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE WAREHOUSE_TO_SUSPEND SUSPEND
USE WAREHOUSE LTHDB_TEST_WH
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE WAREHOUSE_TO_SUSPEND RESUME
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE WAREHOUSE_TO_ALTER UNSET COMMENT
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_ALTER
DROP WAREHOUSE IF EXISTS WAREHOUSE_RENAMED
DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_SUSPEND
USE WAREHOUSE LTHDB_TEST_WH
