CREATE TABLE LTHDB.TEST_ALTERTABLEENHANCED.ENHANCED_TEST_TABLE (id INT, name VARCHAR(100), description VARCHAR(255), created_date date);
ALTER TABLE LTHDB.TEST_ALTERTABLEENHANCED.ENHANCED_TEST_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 30, CHANGE_TRACKING = TRUE, ENABLE_SCHEMA_EVOLUTION = TRUE, MAX_DATA_EXTENSION_TIME_IN_DAYS = 60, DEFAULT_DDL_COLLATION = 'utf8_general_ci';
ALTER TABLE LTHDB.TEST_ALTERTABLEENHANCED.ENHANCED_TEST_TABLE CLUSTER BY (id,name,created_date);
DROP TABLE LTHDB.TEST_ALTERTABLEENHANCED.ENHANCED_TEST_TABLE;