USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP WAREHOUSE IF EXISTS LTHDB_ALTER_TEST_WH
CREATE WAREHOUSE LTHDB_ALTER_TEST_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Warehouse to be altered'
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET WAREHOUSE_SIZE = MEDIUM
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET AUTO_SUSPEND = 300, AUTO_RESUME = true, COMMENT = 'Modified test warehouse'
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET WAREHOUSE_TYPE = STANDARD, MAX_CLUSTER_COUNT = 4, MIN_CLUSTER_COUNT = 1, SCALING_POLICY = ECONOMY
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_ALTER_TEST_WH
USE WAREHOUSE LTHDB_TEST_WH
