CREATE WAREHOUSE LTHDB_ALTER_TEST_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true COMMENT = 'Warehouse to be altered'
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET WAREHOUSE_SIZE = MEDIUM
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET AUTO_SUSPEND = 300, AUTO_RESUME = false, COMMENT = 'Modified test warehouse'
USE WAREHOUSE LTHDB_TEST_WH
ALTER WAREHOUSE LTHDB_ALTER_TEST_WH SET WAREHOUSE_TYPE = STANDARD, MAX_CLUSTER_COUNT = 4, MIN_CLUSTER_COUNT = 1, SCALING_POLICY = ECONOMY
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_ALTER_TEST_WH