CREATE FILE FORMAT TEST_ALTER_FORMAT TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 TRIM_SPACE = false COMMENT = 'Initial format to be altered'
ALTER FILE FORMAT TEST_ALTER_FORMAT SET TRIM_SPACE = true FIELD_DELIMITER = '|' SKIP_HEADER = 2 COMMENT = 'Modified CSV format with new properties'
DROP FILE FORMAT IF EXISTS TEST_ALTER_FORMAT