CREATE FILE FORMAT IF NOT EXISTS PUBLIC.ItTestFileFormat TYPE = CSV
COMPRESSION = ZSTD
BINARY_FORMAT = BASE64
COMMENT = 'myComment'
ALTER FILE FORMAT PUBLIC.ItTestFileFormat SET
COMPRESSION = DEFLATE
COMMENT = 'changedComment'