CREATE TABLE LTHDB.TEST_ALTERTABLESCHEMAEVOLUTION.EVOLUTION_TEST_TABLE (id INT, name VARCHAR(100));
ALTER TABLE LTHDB.TEST_ALTERTABLESCHEMAEVOLUTION.EVOLUTION_TEST_TABLE SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE LTHDB.TEST_ALTERTABLESCHEMAEVOLUTION.EVOLUTION_TEST_TABLE SET ENABLE_SCHEMA_EVOLUTION = FALSE;