DROP DATABASE IF EXISTS LTHDB_ALTER_TEST_DB
DROP DATABASE IF EXISTS LTHDB_ALTER_TEST_DB_RENAMED
CREATE DATABASE LTHDB_ALTER_TEST_DB COMMENT = 'Database to be altered'
ALTER DATABASE LTHDB_ALTER_TEST_DB RENAME TO LTHDB_ALTER_TEST_DB_RENAMED
ALTER DATABASE LTHDB_ALTER_TEST_DB_RENAMED SET COMMENT = 'Modified test database'
ALTER DATABASE LTHDB_ALTER_TEST_DB_RENAMED SET DATA_RETENTION_TIME_IN_DAYS = 30
DROP DATABASE IF EXISTS LTHDB_ALTER_TEST_DB_RENAMED
