DROP TABLE IF EXISTS LTHDB.TESTHARNESS.test_cluster_table CASCADE;

CREATE TABLE LTHDB.TESTHARNESS.test_cluster_table (id INT NOT NULL, region VARCHAR(50) NOT NULL, product VARCHAR(100) NOT NULL, sales_date DATE NOT NULL, CONSTRAINT PK_TEST_CLUSTER_TABLE PRIMARY KEY (id));

ALTER TABLE LTHDB.TESTHARNESS.test_cluster_table CLUSTER BY (region, product);

ALTER TABLE LTHDB.TESTHARNESS.test_cluster_table SUSPEND RECLUSTER;

ALTER TABLE LTHDB.TESTHARNESS.test_cluster_table RESUME RECLUSTER;

ALTER TABLE LTHDB.TESTHARNESS.test_cluster_table DROP CLUSTERING KEY;