CREATE OR ALTER FILE FORMAT ItTestFileFormat TYPE = CSV FIELD_DELIMITER = '|' SKIP_HEADER = 1 NULL_IF = ('NULL', 'null') EMPTY_FIELD_AS_NULL = true COMPRESSION = DEFLATE
CREATE OR ALTER TAG T1 ALLOWED_VALUES 'INTERNAL', 'AWS', 'AWS_COMPAT', 'AZURE', 'GCP'
CREATE OR REPLACE STAGE PUBLIC.testAwsStage URL = 's3://liquibase-dev-snowflake-data/' STORAGE_INTEGRATION = aws_snowflake_integration ENCRYPTION = ( TYPE = 'AWS_SSE_S3' ) DIRECTORY = ( ENABLE = true AUTO_REFRESH = true ) FILE_FORMAT = ( FORMAT_NAME = PUBLIC.ItTestFileFormat TYPE = CSV
SKIP_HEADER = 2
COMPRESSION = GZIP
) WITH TAG (
T1 = 'INTERNAL')
ALTER STAGE PUBLIC.testAwsStage SET TAG T1 = 'AWS'
ALTER STAGE PUBLIC.testAwsStage UNSET TAG T2
ALTER STAGE PUBLIC.testAwsStage SET COMMENT = NULL
ALTER STAGE PUBLIC.testAwsStage SET COMMENT = 'ABC!@'
ALTER STAGE PUBLIC.testAwsStage SET ENCRYPTION = ( TYPE = 'NONE' )
ALTER STAGE PUBLIC.testAwsStage SET FILE_FORMAT = ( TYPE = CSV
SKIP_HEADER = 1
)
ALTER STAGE PUBLIC.testAwsStage RENAME TO PUBLIC.testAwsStage_NEW