CREATE TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_CLUSTER (id INT, name VARCHAR(50), created_date date, region VARCHAR(20))
CREATE TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_PROPERTIES (id INT, data VARCHAR(100), timestamp timestamp)
CREATE TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_COMBINED (id INT, name VARCHAR(50), value DECIMAL(10, 2))
CREATE TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_DROP_CLUSTER (id INT, name VARCHAR(50), value DECIMAL(10, 2))
ALTER TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_CLUSTER CLUSTER BY (region,created_date)
ALTER TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_DROP_CLUSTER DROP CLUSTERING KEY
ALTER TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_PROPERTIES SET DATA_RETENTION_TIME_IN_DAYS = 30, CHANGE_TRACKING = TRUE, ENABLE_SCHEMA_EVOLUTION = FALSE
ALTER TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_COMBINED CLUSTER BY (id,value)
ALTER TABLE LTHDB.TEST_ALTERTABLE.TEST_TABLE_COMBINED SET DATA_RETENTION_TIME_IN_DAYS = 7, CHANGE_TRACKING = FALSE