CREATE TABLE LTHDB.TEST_ALTERTABLEMULTIOPERATION.MULTI_OP_TEST_TABLE (id INT, name VARCHAR(100), description VARCHAR(255));
ALTER TABLE LTHDB.TEST_ALTERTABLEMULTIOPERATION.MULTI_OP_TEST_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 14, CHANGE_TRACKING = TRUE, ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE LTHDB.TEST_ALTERTABLEMULTIOPERATION.MULTI_OP_TEST_TABLE CLUSTER BY (id,name);
ALTER TABLE LTHDB.TEST_ALTERTABLEMULTIOPERATION.MULTI_OP_TEST_TABLE DROP CLUSTERING KEY;