USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP SCHEMA IF EXISTS TEST_ALTER_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_RENAME_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_RENAMED_SCHEMA CASCADE
CREATE SCHEMA IF NOT EXISTS TEST_ALTER_SCHEMA
COMMENT = 'Initial schema for alter tests'
DATA_RETENTION_TIME_IN_DAYS = 7
CREATE SCHEMA IF NOT EXISTS TEST_RENAME_SCHEMA
WITH MANAGED ACCESS
COMMENT = 'Schema to be renamed'
ALTER SCHEMA TEST_ALTER_SCHEMA SET COMMENT = 'Modified schema comment'
ALTER SCHEMA TEST_ALTER_SCHEMA SET DATA_RETENTION_TIME_IN_DAYS = 30
ALTER SCHEMA TEST_ALTER_SCHEMA ENABLE MANAGED ACCESS
ALTER SCHEMA TEST_RENAME_SCHEMA RENAME TO TEST_RENAMED_SCHEMA
ALTER SCHEMA TEST_ALTER_SCHEMA UNSET COMMENT
DROP SCHEMA TEST_ALTER_SCHEMA
DROP SCHEMA TEST_RENAMED_SCHEMA
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)