CREATE TABLE LTHDB.TEST_ALTERTABLEADVANCED.ADVANCED_TEST_TABLE (id INT, user_id VARCHAR(100), department VARCHAR(100), data VARCHAR(255), location GEOGRAPHY);
ALTER TABLE LTHDB.TEST_ALTERTABLEADVANCED.ADVANCED_TEST_TABLE ADD SEARCH OPTIMIZATION ON EQUALITY(user_id, department);
ALTER TABLE LTHDB.TEST_ALTERTABLEADVANCED.ADVANCED_TEST_TABLE DROP SEARCH OPTIMIZATION;
DROP TABLE LTHDB.TEST_ALTERTABLEADVANCED.ADVANCED_TEST_TABLE;