-- Liquibase Snowflake SQL
-- MUST include ALL SQL including init.xml
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
-- Cleanup SQL
DROP TABLE IF EXISTS LTHDB.TESTHARNESS.TEST_TABLE_CLUSTER CASCADE
DROP TABLE IF EXISTS LTHDB.TESTHARNESS.TEST_TABLE_PROPERTIES CASCADE
DROP TABLE IF EXISTS LTHDB.TESTHARNESS.TEST_TABLE_COMBINED CASCADE
DROP TABLE IF EXISTS LTHDB.TESTHARNESS.TEST_TABLE_DROP_CLUSTER CASCADE
-- Create test tables SQL
CREATE TABLE LTHDB.TESTHARNESS.TEST_TABLE_CLUSTER (
id INT,
name VARCHAR(50),
created_date DATE,
region VARCHAR(20)
)
CREATE TABLE LTHDB.TESTHARNESS.TEST_TABLE_PROPERTIES (
id INT,
data VARCHAR(100),
timestamp TIMESTAMP
)
CREATE TABLE LTHDB.TESTHARNESS.TEST_TABLE_COMBINED (
id INT,
name VARCHAR(50),
value DECIMAL(10,2)
)
CREATE TABLE LTHDB.TESTHARNESS.TEST_TABLE_DROP_CLUSTER (
id INT,
name VARCHAR(50),
value DECIMAL(10,2)
) CLUSTER BY (id, name)
-- Test SQL: Basic clustering
ALTER TABLE LTHDB.TESTHARNESS.TEST_TABLE_CLUSTER CLUSTER BY (region,created_date)
-- Test SQL: Drop clustering key
ALTER TABLE LTHDB.TESTHARNESS.TEST_TABLE_DROP_CLUSTER DROP CLUSTERING KEY
-- Test SQL: Property settings
ALTER TABLE LTHDB.TESTHARNESS.TEST_TABLE_PROPERTIES SET DATA_RETENTION_TIME_IN_DAYS = 30, CHANGE_TRACKING = TRUE, ENABLE_SCHEMA_EVOLUTION = FALSE
-- Test SQL: Combined operations
ALTER TABLE LTHDB.TESTHARNESS.TEST_TABLE_COMBINED CLUSTER BY (id,value)
ALTER TABLE LTHDB.TESTHARNESS.TEST_TABLE_COMBINED SET DATA_RETENTION_TIME_IN_DAYS = 7, CHANGE_TRACKING = FALSE