DROP DATABASE IF EXISTS LTHDB_TEST_DATABASE
DROP DATABASE IF EXISTS LTHDB_TEST_TRANSIENT_DB
DROP DATABASE IF EXISTS LTHDB_TEST_RETENTION_DB
DROP DATABASE IF EXISTS LTHDB_TEST_FULL_FEATURE_DB
CREATE DATABASE LTHDB_TEST_DATABASE COMMENT = 'Basic test database'
CREATE TRANSIENT DATABASE LTHDB_TEST_TRANSIENT_DB COMMENT = 'Transient test database'
CREATE DATABASE LTHDB_TEST_RETENTION_DB DATA_RETENTION_TIME_IN_DAYS = 7 COMMENT = 'Database with data retention'
CREATE DATABASE LTHDB_TEST_FULL_FEATURE_DB DATA_RETENTION_TIME_IN_DAYS = 14 COMMENT = 'Full featured database'
