DROP WAREHOUSE IF EXISTS LTHDB_TEST_WAREHOUSE
DROP WAREHOUSE IF EXISTS LTHDB_TEST_MULTICLUSTER_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_ADVANCED_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_RESOURCE_CONSTRAINT_WH
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE LTHDB_TEST_WAREHOUSE WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Test warehouse for harness'
CREATE WAREHOUSE LTHDB_TEST_MULTICLUSTER_WH WITH WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = MEDIUM MAX_CLUSTER_COUNT = 3 MIN_CLUSTER_COUNT = 1 SCALING_POLICY = STANDARD AUTO_SUSPEND = 300 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Multi-cluster test warehouse'
CREATE WAREHOUSE LTHDB_TEST_ADVANCED_WH WITH WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED' WAREHOUSE_SIZE = LARGE COMMENT = 'Advanced options test warehouse' ENABLE_QUERY_ACCELERATION = true QUERY_ACCELERATION_MAX_SCALE_FACTOR = 4 MAX_CONCURRENCY_LEVEL = 8 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300 STATEMENT_TIMEOUT_IN_SECONDS = 600