CREATE TABLE LB_DBEXT_INT_DB.TEST_CREATETABLESIMPLE.SIMPLE_TEST_TABLE (id INT NOT NULL, name VARCHAR(100) NOT NULL, description TEXT, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT PK_SIMPLE_TEST_TABLE PRIMARY KEY (id))
CREATE TABLE LB_DBEXT_INT_DB.TEST_CREATETABLESIMPLE.CONFIGURED_TEST_TABLE (id BIGINT NOT NULL, status VARCHAR(20) DEFAULT 'ACTIVE', amount DECIMAL(10,2), CONSTRAINT PK_CONFIGURED_TEST_TABLE PRIMARY KEY (id))
DROP TABLE LB_DBEXT_INT_DB.TEST_CREATETABLESIMPLE.SIMPLE_TEST_TABLE
DROP TABLE LB_DBEXT_INT_DB.TEST_CREATETABLESIMPLE.CONFIGURED_TEST_TABLE
EOF < /dev/null