DROP WAREHOUSE IF EXISTS LTHDB_TEST_RESOURCE_CONSTRAINT_WH
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE LTHDB_TEST_RESOURCE_CONSTRAINT_WH WITH WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED' WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false RESOURCE_CONSTRAINT = MEMORY_1X COMMENT = 'Test warehouse with resource constraint'
