CREATE OR ALTER FILE FORMAT ItTestFileFormat
TYPE = CSV
FIELD_DELIMITER = '|'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = true
COMPRESSION = DEFLATE
CREATE OR ALTER TAG T1 ALLOWED_VALUES 'INTERNAL', 'AWS', 'AWS_COMPAT', 'AZURE', 'GCP'
CREATE STAGE PUBLIC.testStage ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' ) DIRECTORY = ( ENABLE = true AUTO_REFRESH = true ) FILE_FORMAT = ( FORMAT_NAME = PUBLIC.ItTestFileFormat TYPE = CSV
COMPRESSION = GZIP
SKIP_HEADER = 2
) WITH TAG (
T1 = 'INTERNAL')
