CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_BASIC_WH
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_SIZED_WH WITH WAREHOUSE_SIZE = SMALL AUTO_SUSPEND = 300 AUTO_RESUME = true
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_MULTICLUSTER_WH WITH WAREHOUSE_SIZE = SMALL MAX_CLUSTER_COUNT = 3 MIN_CLUSTER_COUNT = 1 SCALING_POLICY = STANDARD
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_SUSPENDED_WH WITH INITIALLY_SUSPENDED = true COMMENT = 'Start suspended to save costs'
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_ACCELERATED_WH WITH WAREHOUSE_SIZE = SMALL ENABLE_QUERY_ACCELERATION = true QUERY_ACCELERATION_MAX_SCALE_FACTOR = 10
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_SNOWPARK_WH WITH WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED' WAREHOUSE_SIZE = MEDIUM
CREATE OR REPLACE WAREHOUSE CREATEWAREHOUSE_REPLACE_WH WITH WAREHOUSE_SIZE = SMALL COMMENT = 'Replaced warehouse'
CREATE WAREHOUSE IF NOT EXISTS CREATEWAREHOUSE_IFNOTEXISTS_WH WITH WAREHOUSE_SIZE = XSMALL
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_BASIC_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_SIZED_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_MULTICLUSTER_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_SUSPENDED_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_ACCELERATED_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_SNOWPARK_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_REPLACE_WH
DROP WAREHOUSE IF EXISTS CREATEWAREHOUSE_IFNOTEXISTS_WH
USE WAREHOUSE LTHDB_TEST_WH