CREATE TRANSIENT TABLE TEST_CREATETABLENAMESPACE.TRANSIENT_SESSIONS (user_id INT NOT NULL, session_start TIMESTAMP NOT NULL, session_data VARCHAR(1000)) CLUSTER BY (user_id,session_start)
CREATE TABLE TEST_CREATETABLENAMESPACE.CUSTOMER_ORDERS (order_id INT AUTOINCREMENT, customer_id INT NOT NULL, order_date DATE, total_amount DECIMAL(10,2), PRIMARY KEY (order_id)) CHANGE_TRACKING = true DATA_RETENTION_TIME_IN_DAYS = 7 MAX_DATA_EXTENSION_TIME_IN_DAYS = 30
CREATE TEMPORARY TABLE TEST_CREATETABLENAMESPACE.TEMP_CALCULATIONS (calc_id INT, result DECIMAL(10,2), computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP())
CREATE TABLE TEST_CREATETABLENAMESPACE.EVOLVING_SCHEMA (id VARCHAR(36), data VARIANT, metadata OBJECT, PRIMARY KEY (id)) ENABLE_SCHEMA_EVOLUTION = true DEFAULT_DDL_COLLATION = 'en-ci'
CREATE VOLATILE TABLE TEST_CREATETABLENAMESPACE.VOLATILE_STAGING (staging_id INT, raw_data TEXT)
CREATE TABLE TEST_CREATETABLENAMESPACE.MULTI_FEATURE_TABLE (id INT AUTOINCREMENT, created_date DATE NOT NULL, status VARCHAR(20), details VARIANT, PRIMARY KEY (id)) CLUSTER BY (id,created_date) CHANGE_TRACKING = true DATA_RETENTION_TIME_IN_DAYS = 14 COPY GRANTS
DROP TABLE TEST_CREATETABLENAMESPACE.TRANSIENT_SESSIONS
DROP TABLE TEST_CREATETABLENAMESPACE.CUSTOMER_ORDERS
DROP TABLE TEST_CREATETABLENAMESPACE.TEMP_CALCULATIONS
DROP TABLE TEST_CREATETABLENAMESPACE.EVOLVING_SCHEMA
DROP TABLE TEST_CREATETABLENAMESPACE.VOLATILE_STAGING
DROP TABLE TEST_CREATETABLENAMESPACE.MULTI_FEATURE_TABLE