CREATE SEQUENCE TEST_CREATESEQUENCEVALIDATION.VALIDATION_TEST_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEST_CREATESEQUENCEVALIDATION.ANOTHER_VALIDATION_SEQ START WITH 100 INCREMENT BY 5;
CREATE SEQUENCE TEST_CREATESEQUENCEVALIDATION.ORDER_TEST_SEQ START WITH 1000 INCREMENT BY 1;