CREATE SEQUENCE TEST_ORDERED_NEGATIVE
START WITH 1000
INCREMENT BY -10
ORDER
CREATE SEQUENCE TEST_ORDERED_CYCLE
START WITH 1
INCREMENT BY 1
ORDER
COMMENT = 'Ordered sequence for testing'
DROP SEQUENCE TESTHARNESS.TEST_ORDERED_SEQUENCE
DROP SEQUENCE TESTHARNESS.TEST_NOORDER_SEQUENCE
DROP SEQUENCE TESTHARNESS.TEST_ORDERED_COMPLEX
DROP SEQUENCE TESTHARNESS.TEST_ALTER_ORDER_SEQ
DROP SEQUENCE TESTHARNESS.TEST_ORDERED_NEGATIVE
DROP SEQUENCE TESTHARNESS.TEST_ORDERED_CYCLE