DROP WAREHOUSE IF EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE IF NOT EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true COMMENT = 'Test warehouse with IF NOT EXISTS'
CREATE WAREHOUSE IF NOT EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH WITH WAREHOUSE_SIZE = SMALL AUTO_SUSPEND = 120 AUTO_RESUME = true COMMENT = 'Duplicate creation should not fail'
