USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP WAREHOUSE IF EXISTS LTHDB_TEST_WAREHOUSE
DROP WAREHOUSE IF EXISTS LTHDB_TEST_MULTICLUSTER_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_ADVANCED_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH
DROP WAREHOUSE IF EXISTS LTHDB_TEST_RESOURCE_CONSTRAINT_WH
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE LTHDB_TEST_WAREHOUSE WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Test warehouse for harness'
CREATE WAREHOUSE LTHDB_TEST_MULTICLUSTER_WH WITH WAREHOUSE_TYPE = 'STANDARD' WAREHOUSE_SIZE = MEDIUM MAX_CLUSTER_COUNT = 3 MIN_CLUSTER_COUNT = 1 SCALING_POLICY = STANDARD AUTO_SUSPEND = 300 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Multi-cluster test warehouse'
CREATE WAREHOUSE LTHDB_TEST_ADVANCED_WH WITH WAREHOUSE_TYPE = 'STANDARD' WAREHOUSE_SIZE = LARGE AUTO_SUSPEND = 180 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Advanced configuration warehouse' MAX_CONCURRENCY_LEVEL = 8 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 3600 STATEMENT_TIMEOUT_IN_SECONDS = 172800
CREATE WAREHOUSE IF NOT EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true COMMENT = 'Test warehouse with IF NOT EXISTS'
CREATE WAREHOUSE IF NOT EXISTS LTHDB_TEST_IF_NOT_EXISTS_WH WITH WAREHOUSE_SIZE = MEDIUM AUTO_SUSPEND = 120 COMMENT = 'Duplicate creation should not fail'
CREATE WAREHOUSE LTHDB_TEST_RESOURCE_CONSTRAINT_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Test warehouse with resource constraint'