USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
CREATE SEQUENCE TESTHARNESS.TEST_BASIC_SEQUENCE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE TESTHARNESS.TEST_INCREMENT_SEQUENCE START WITH 100 INCREMENT BY 5
CREATE SEQUENCE TESTHARNESS.TEST_START_SEQUENCE START WITH 1000 INCREMENT BY 1
DROP SEQUENCE TESTHARNESS.TEST_BASIC_SEQUENCE
DROP SEQUENCE TESTHARNESS.TEST_INCREMENT_SEQUENCE
DROP SEQUENCE TESTHARNESS.TEST_START_SEQUENCE
