CREATE SCHEMA BASIC_SCHEMA
CREATE SCHEMA CONFIGURED_SCHEMA DATA_RETENTION_TIME_IN_DAYS = 7 MAX_DATA_EXTENSION_TIME_IN_DAYS = 30 COMMENT = 'Test schema with configuration'
CREATE TRANSIENT SCHEMA TRANSIENT_SCHEMA COMMENT = 'Transient schema for testing'
CREATE SCHEMA MANAGED_SCHEMA WITH MANAGED ACCESS COMMENT = 'Managed access schema'
CREATE OR REPLACE SCHEMA REPLACE_SCHEMA COMMENT = 'Schema with OR REPLACE'
CREATE SCHEMA IF NOT EXISTS IF_NOT_EXISTS_SCHEMA DATA_RETENTION_TIME_IN_DAYS = 14 DEFAULT_DDL_COLLATION = 'utf8'
CREATE SCHEMA CLONE_SCHEMA CLONE BASIC_SCHEMA COMMENT = 'Cloned schema for testing'
DROP SCHEMA CLONE_SCHEMA
DROP SCHEMA IF_NOT_EXISTS_SCHEMA
DROP SCHEMA REPLACE_SCHEMA
DROP SCHEMA MANAGED_SCHEMA
DROP SCHEMA TRANSIENT_SCHEMA
DROP SCHEMA CONFIGURED_SCHEMA
DROP SCHEMA BASIC_SCHEMA