USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP SCHEMA IF EXISTS TEST_TRANSIENT_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_MANAGED_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_MANAGED_SCHEMA_RENAMED CASCADE
DROP SCHEMA IF EXISTS TEST_RETENTION_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_FULL_SCHEMA CASCADE
CREATE TRANSIENT SCHEMA TEST_TRANSIENT_SCHEMA COMMENT = 'Transient test schema'
CREATE SCHEMA TEST_MANAGED_SCHEMA WITH MANAGED ACCESS COMMENT = 'Managed access schema'
CREATE SCHEMA TEST_RETENTION_SCHEMA DATA_RETENTION_TIME_IN_DAYS = 7 COMMENT = 'Schema with retention'
CREATE TRANSIENT SCHEMA TEST_FULL_SCHEMA WITH MANAGED ACCESS COMMENT = 'Full featured schema'
ALTER SCHEMA TEST_TRANSIENT_SCHEMA SET COMMENT = 'Modified transient schema'
ALTER SCHEMA TEST_RETENTION_SCHEMA SET DATA_RETENTION_TIME_IN_DAYS = 21
ALTER SCHEMA TEST_MANAGED_SCHEMA RENAME TO TEST_MANAGED_SCHEMA_RENAMED
DROP SCHEMA TEST_TRANSIENT_SCHEMA
DROP SCHEMA TEST_MANAGED_SCHEMA_RENAMED
DROP SCHEMA TEST_RETENTION_SCHEMA
DROP SCHEMA TEST_FULL_SCHEMA
