USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TEST_CreateSequenceEnhanced CASCADE
CREATE SCHEMA TEST_CreateSequenceEnhanced
USE SCHEMA TEST_CreateSequenceEnhanced
GRANT ALL PRIVILEGES ON SCHEMA TEST_CreateSequenceEnhanced TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
CREATE SEQUENCE TEST_CreateSequenceEnhanced.TEST_BASIC_SEQUENCE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE TEST_CreateSequenceEnhanced.TEST_ORDERED_SEQUENCE START WITH 100 INCREMENT BY 5 ORDER
CREATE SEQUENCE TEST_CreateSequenceEnhanced.TEST_NOORDER_SEQUENCE START WITH 1000 INCREMENT BY 1 NOORDER
DROP SEQUENCE TEST_CreateSequenceEnhanced.TEST_BASIC_SEQUENCE
DROP SEQUENCE TEST_CreateSequenceEnhanced.TEST_ORDERED_SEQUENCE
DROP SEQUENCE TEST_CreateSequenceEnhanced.TEST_NOORDER_SEQUENCE
