CREATE DATABASE BASIC_DB
CREATE DATABASE CONFIGURED_DB DATA_RETENTION_TIME_IN_DAYS = 7 COMMENT = 'Test database with configuration'
CREATE TRANSIENT DATABASE TRANSIENT_DB COMMENT = 'Transient database for testing'
CREATE OR REPLACE DATABASE REPLACE_DB COMMENT = 'Database with OR REPLACE'
CREATE DATABASE IF NOT EXISTS IF_NOT_EXISTS_DB DATA_RETENTION_TIME_IN_DAYS = 14 MAX_DATA_EXTENSION_TIME_IN_DAYS = 90
CREATE DATABASE CLONE_DB COMMENT = 'Cloned database for testing'
DROP DATABASE IF EXISTS BASIC_DB
DROP DATABASE IF EXISTS CONFIGURED_DB
DROP DATABASE IF EXISTS TRANSIENT_DB
DROP DATABASE IF EXISTS REPLACE_DB
DROP DATABASE IF EXISTS IF_NOT_EXISTS_DB
DROP DATABASE IF EXISTS CLONE_DB
