DROP SCHEMA IF EXISTS TEST_SCHEMA CASCADE
DROP SCHEMA IF EXISTS SCHEMA_WITH_COMMENT CASCADE
DROP SCHEMA IF EXISTS TRANSIENT_SCHEMA CASCADE
DROP SCHEMA IF EXISTS MANAGED_SCHEMA CASCADE
DROP SCHEMA IF EXISTS RETENTION_SCHEMA CASCADE
CREATE SCHEMA TEST_SCHEMA
CREATE SCHEMA SCHEMA_WITH_COMMENT COMMENT = 'This is a test schema with comment'
CREATE TRANSIENT SCHEMA TRANSIENT_SCHEMA
CREATE SCHEMA MANAGED_SCHEMA WITH MANAGED ACCESS COMMENT = 'Schema with managed access'
CREATE SCHEMA RETENTION_SCHEMA DATA_RETENTION_TIME_IN_DAYS = 7 COMMENT = 'Schema with 7 day retention'