CREATE TRANSIENT SCHEMA TEST_FULL_SCHEMA WITH MANAGED ACCESS COMMENT = 'Full featured schema'
ALTER SCHEMA TEST_TRANSIENT_SCHEMA SET COMMENT = 'Modified transient schema'
ALTER SCHEMA TEST_RETENTION_SCHEMA SET DATA_RETENTION_TIME_IN_DAYS = 21
ALTER SCHEMA TEST_MANAGED_SCHEMA RENAME TO TEST_MANAGED_SCHEMA_RENAMED
DROP SCHEMA IF EXISTS TEST_TRANSIENT_SCHEMA
DROP SCHEMA IF EXISTS TEST_MANAGED_SCHEMA_RENAMED
DROP SCHEMA IF EXISTS TEST_RETENTION_SCHEMA
DROP SCHEMA IF EXISTS TEST_FULL_SCHEMA