CREATE TABLE LTHDB.TESTHARNESS.STANDARD_TABLE (id INT);

CREATE TABLE LTHDB.TESTHARNESS.SNOWFLAKE_TABLE (id INT);

CREATE TRANSIENT TABLE LTHDB.TESTHARNESS.SNOWFLAKE_TABLE_WITH_ATTRS (id INT) COMMENT='Test table';