DROP SCHEMA IF EXISTS TEST_DROP_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_CASCADE_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_RESTRICT_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_IF_EXISTS_SCHEMA CASCADE
CREATE SCHEMA IF NOT EXISTS TEST_DROP_SCHEMA COMMENT = 'Schema to be dropped'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_CASCADE_SCHEMA COMMENT = 'Schema to be dropped with cascade'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_RESTRICT_SCHEMA COMMENT = 'Schema to be dropped with restrict'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_IF_EXISTS_SCHEMA COMMENT = 'Schema to test IF EXISTS'
CREATE TABLE LTHDB.TEST_DROP_CASCADE_SCHEMA.TEST_TABLE (id INT NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (id))
DROP SCHEMA TEST_DROP_SCHEMA
DROP SCHEMA TEST_DROP_CASCADE_SCHEMA CASCADE
DROP SCHEMA TEST_DROP_RESTRICT_SCHEMA
DROP SCHEMA IF EXISTS TEST_DROP_IF_EXISTS_SCHEMA
DROP SCHEMA IF EXISTS NON_EXISTENT_SCHEMA