ALTER TABLE ${CATALOG_NAME}.${SCHEMA_NAME}.posts ADD varcharColumn VARCHAR(25)
UPDATE ${CATALOG_NAME}.${SCHEMA_NAME}.posts SET varcharColumn = 'INITIAL_VALUE'
ALTER TABLE ${CATALOG_NAME}.${SCHEMA_NAME}.posts DROP COLUMN varcharColumn