USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP DATABASE IF EXISTS LTHDB_DROP_TEST_DB
DROP DATABASE IF EXISTS LTHDB_NONEXISTENT_DB
DROP DATABASE IF EXISTS LTHDB_CASCADE_TEST_DB
CREATE DATABASE LTHDB_DROP_TEST_DB COMMENT = 'Database to be dropped'
DROP DATABASE LTHDB_DROP_TEST_DB
DROP DATABASE IF EXISTS LTHDB_NONEXISTENT_DB
CREATE DATABASE LTHDB_CASCADE_TEST_DB COMMENT = 'Database with objects'
DROP DATABASE LTHDB_CASCADE_TEST_DB CASCADE
