CREATE TABLE LTHDB.TESTHARNESS.authors (id INT NOT NULL, email VARCHAR(100) NOT NULL, name VARCHAR(100), CONSTRAINT PK_AUTHORS PRIMARY KEY (id))
CREATE TABLE LTHDB.TESTHARNESS.posts (id INT NOT NULL, author_id INT NOT NULL, title VARCHAR(255), content TEXT, CONSTRAINT PK_POSTS PRIMARY KEY (id))
ALTER TABLE LTHDB.TESTHARNESS.posts ADD CONSTRAINT fk_posts_authors_test FOREIGN KEY (author_id) REFERENCES LTHDB.TESTHARNESS.authors (id)
ALTER TABLE LTHDB.TESTHARNESS.posts DROP CONSTRAINT fk_posts_authors_test