USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
DROP SCHEMA IF EXISTS TEST_DROP_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_CASCADE_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_RESTRICT_SCHEMA CASCADE
DROP SCHEMA IF EXISTS TEST_DROP_IF_EXISTS_SCHEMA CASCADE
CREATE SCHEMA IF NOT EXISTS TEST_DROP_SCHEMA COMMENT = 'Schema to be dropped'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_CASCADE_SCHEMA COMMENT = 'Schema to be dropped with cascade'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_RESTRICT_SCHEMA COMMENT = 'Schema to be dropped with restrict'
CREATE SCHEMA IF NOT EXISTS TEST_DROP_IF_EXISTS_SCHEMA COMMENT = 'Schema to test IF EXISTS'
CREATE TABLE LTHDB.TEST_DROP_CASCADE_SCHEMA.TEST_TABLE (id INT NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (id))
DROP SCHEMA TEST_DROP_SCHEMA
DROP SCHEMA TEST_DROP_CASCADE_SCHEMA CASCADE
DROP SCHEMA TEST_DROP_RESTRICT_SCHEMA
DROP SCHEMA IF EXISTS TEST_DROP_IF_EXISTS_SCHEMA
DROP SCHEMA IF EXISTS NON_EXISTENT_SCHEMA
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)