DELETE FROM DATABASECHANGELOG WHERE FILENAME NOT LIKE '%init.xml'
UPDATE DATABASECHANGELOGLOCK SET LOCKED = FALSE WHERE ID = 1
CREATE SEQUENCE LTHDB.TESTHARNESS.test_drop_sequence_restrict INCREMENT BY 1 START WITH 1
DROP SEQUENCE LTHDB.TESTHARNESS.test_drop_sequence_restrict RESTRICT