USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_DROP_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_NONEXISTENT_WH
CREATE WAREHOUSE LTHDB_DROP_TEST_WH WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = true INITIALLY_SUSPENDED = false COMMENT = 'Warehouse to be dropped'
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_DROP_TEST_WH
DROP WAREHOUSE IF EXISTS LTHDB_NONEXISTENT_WH
USE WAREHOUSE LTHDB_TEST_WH
