DROP WAREHOUSE IF EXISTS WAREHOUSE_TO_DROP
DROP WAREHOUSE IF EXISTS WAREHOUSE_IF_EXISTS
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_1
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_2
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_3
USE WAREHOUSE LTHDB_TEST_WH
CREATE WAREHOUSE WAREHOUSE_TO_DROP
CREATE WAREHOUSE WAREHOUSE_IF_EXISTS
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE WAREHOUSE_TO_DROP
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS WAREHOUSE_IF_EXISTS
USE WAREHOUSE LTHDB_TEST_WH
DROP WAREHOUSE IF EXISTS NONEXISTENT_WAREHOUSE
CREATE WAREHOUSE TEMP_WAREHOUSE_1 WITH WAREHOUSE_SIZE = XSMALL
CREATE WAREHOUSE TEMP_WAREHOUSE_2 WITH WAREHOUSE_SIZE = XSMALL
CREATE WAREHOUSE TEMP_WAREHOUSE_3 WITH WAREHOUSE_SIZE = XSMALL
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_1
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_2
DROP WAREHOUSE IF EXISTS TEMP_WAREHOUSE_3
USE WAREHOUSE LTHDB_TEST_WH
