DROP DATABASE IF EXISTS LTHDB_DROP_TEST_DB
DROP DATABASE IF EXISTS LTHDB_NONEXISTENT_DB
DROP DATABASE IF EXISTS LTHDB_CASCADE_TEST_DB
CREATE DATABASE LTHDB_DROP_TEST_DB COMMENT = 'Database to be dropped'
DROP DATABASE LTHDB_DROP_TEST_DB
DROP DATABASE IF EXISTS LTHDB_NONEXISTENT_DB
CREATE DATABASE LTHDB_CASCADE_TEST_DB COMMENT = 'Database with objects'
DROP DATABASE LTHDB_CASCADE_TEST_DB CASCADE
