ALTER TABLE ${CATALOG_NAME}.PUBLIC.posts ADD varcharColumn VARCHAR(25)
UPDATE ${CATALOG_NAME}.PUBLIC.posts SET varcharColumn = 'INITIAL_VALUE'
ALTER TABLE ${CATALOG_NAME}.PUBLIC.posts DROP COLUMN varcharColumn