CREATE TABLE LTHDB.TEST_MODIFYDATATYPESNOWFLAKE.MODIFY_TYPE_TEST_TABLE (int_col INT, varchar_col VARCHAR(50), number_col NUMBER(10, 2), text_col TEXT);
ALTER TABLE LTHDB.TEST_MODIFYDATATYPESNOWFLAKE.MODIFY_TYPE_TEST_TABLE ALTER COLUMN int_col TYPE BIGINT;
ALTER TABLE LTHDB.TEST_MODIFYDATATYPESNOWFLAKE.MODIFY_TYPE_TEST_TABLE ALTER COLUMN varchar_col TYPE VARCHAR(100);