CREATE TABLE LTHDB.PUBLIC.oldnametable (test_id INT NOT NULL, test_column VARCHAR(50) NOT NULL, CONSTRAINT PK_OLDNAMETABLE PRIMARY KEY (test_id))
ALTER TABLE LTHDB.PUBLIC.oldnametable RENAME TO LTHDB.PUBLIC.newnametable
