CREATE TABLE LTHDB.TEST_SETCOLUMNREMARKS.REMARKS_TEST_TABLE (id INT, name VARCHAR(100), description VARCHAR(255));
COMMENT ON COLUMN LTHDB.TEST_SETCOLUMNREMARKS.REMARKS_TEST_TABLE.id IS 'Primary identifier column';
COMMENT ON COLUMN LTHDB.TEST_SETCOLUMNREMARKS.REMARKS_TEST_TABLE.name IS 'Name field with special characters: äöü';
COMMENT ON COLUMN LTHDB.TEST_SETCOLUMNREMARKS.REMARKS_TEST_TABLE.description IS 'Long description field for additional information';
COMMENT ON COLUMN LTHDB.TEST_SETCOLUMNREMARKS.REMARKS_TEST_TABLE.description IS '';