-- Drop warehouse if it exists from previous test runs
DROP WAREHOUSE IF EXISTS LTHDB_SQL_TEST_WH
-- Drop and recreate schema to ensure clean state
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE
CREATE SCHEMA TESTHARNESS
USE SCHEMA TESTHARNESS
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE IF NOT EXISTS DATABASECHANGELOG ( ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10) )
CREATE TABLE IF NOT EXISTS DATABASECHANGELOGLOCK ( ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), PRIMARY KEY (ID) )
-- Initialize lock table
DELETE FROM DATABASECHANGELOGLOCK
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE)
CREATE WAREHOUSE LTHDB_SQL_TEST_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE COMMENT = 'Test warehouse via SQL'
