USE ROLE LIQUIBASE_TEST_HARNESS_ROLE
DROP SCHEMA IF EXISTS TEST_ValueSequenceNext CASCADE
CREATE SCHEMA TEST_ValueSequenceNext
USE SCHEMA TEST_ValueSequenceNext
GRANT ALL PRIVILEGES ON SCHEMA TEST_ValueSequenceNext TO ROLE LIQUIBASE_TEST_HARNESS_ROLE
CREATE TABLE DATABASECHANGELOG (
ID VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
FILENAME VARCHAR(255) NOT NULL,
DATEEXECUTED TIMESTAMP NOT NULL,
ORDEREXECUTED INT NOT NULL,
EXECTYPE VARCHAR(10) NOT NULL,
MD5SUM VARCHAR(35),
DESCRIPTION VARCHAR(255),
COMMENTS VARCHAR(255),
TAG VARCHAR(255),
LIQUIBASE VARCHAR(20),
CONTEXTS VARCHAR(255),
LABELS VARCHAR(255),
DEPLOYMENT_ID VARCHAR(10)
)
CREATE TABLE DATABASECHANGELOGLOCK (
ID INT NOT NULL,
LOCKED BOOLEAN NOT NULL,
LOCKGRANTED TIMESTAMP,
LOCKEDBY VARCHAR(255),
PRIMARY KEY (ID)
)
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, TRUE)
CREATE TABLE LTHDB.TEST_ValueSequenceNext.valueSequenceNextTable (test_id INT, test_column VARCHAR(50))
CREATE SEQUENCE TEST_ValueSequenceNext.value_test_sequence START WITH 30 INCREMENT BY 2
UPDATE LTHDB.TEST_ValueSequenceNext.valueSequenceNextTable SET test_id = TEST_ValueSequenceNext.value_test_sequence.nextval
