USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:08.498' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE DATABASECHANGELOG (ID nvarchar(255) NOT NULL, AUTHOR nvarchar(255) NOT NULL, FILENAME nvarchar(255) NOT NULL, DATEEXECUTED datetime2(3) NOT NULL, ORDEREXECUTED int NOT NULL, EXECTYPE nvarchar(10) NOT NULL, MD5SUM nvarchar(35), DESCRIPTION nvarchar(255), COMMENTS nvarchar(255), TAG nvarchar(255), LIQUIBASE nvarchar(20), CONTEXTS nvarchar(255), LABELS nvarchar(255), DEPLOYMENT_ID nvarchar(10))
GO
ALTER TABLE authors ADD varcharColumn varchar(25)
GO
ALTER TABLE authors ADD intColumn int
GO
ALTER TABLE authors ADD dateColumn date
GO
UPDATE authors SET varcharColumn = 'INITIAL_VALUE'
GO
UPDATE authors SET intColumn = 5
GO
UPDATE authors SET dateColumn = '2020-09-21'
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'kristyl', 'liquibase/harness/change/changelogs/addColumn.xml', GETDATE(), 1, '8:011837fa9ce01a0edb80358d9f610666', 'addColumn tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725949333')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO