USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:16.518' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE authors ADD booleanColumn bit
GO
ALTER TABLE authors ADD CONSTRAINT DF_authors_booleanColumn DEFAULT 1 FOR booleanColumn
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'as', 'liquibase/harness/change/changelogs/addDefaultValueBoolean.xml', GETDATE(), 1, '8:16811a4e855041563717d347052262f0', 'addColumn tableName=authors addDefaultValue columnName=booleanColumn, tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725957117')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO