USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:28.931' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE authors ADD numericColumn numeric(18, 0)
GO
ALTER TABLE authors ADD CONSTRAINT DF_authors_numericColumn DEFAULT 100000000 FOR numericColumn
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'as', 'liquibase/harness/change/changelogs/addDefaultValueNumeric.xml', GETDATE(), 1, '8:057e8baf7a08b4e8ea8e5c42b9cf12c4', 'addColumn tableName=authors addDefaultValue columnName=numericColumn, tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725969928')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO