USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:19.85' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE posts ADD CONSTRAINT DF_posts_inserted_date DEFAULT GETDATE() FOR inserted_date
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/addDefaultValueComputed.xml', GETDATE(), 1, '8:b791629ff050022cb6fba74c2231561d', 'addDefaultValue columnName=inserted_date, tableName=posts', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725960569')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO