USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:39.376' WHERE ID = 1 AND LOCKED = 0
GO
SELECT DISTINCT email AS authors_email INTO authors_data FROM authors WHERE email IS NOT NULL
GO
ALTER TABLE authors_data ALTER COLUMN authors_email varchar(100) NOT NULL
GO
ALTER TABLE authors_data ADD PRIMARY KEY (authors_email)
GO
ALTER TABLE authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES authors_data (authors_email)
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'as', 'liquibase/harness/change/changelogs/addLookupTable.xml', GETDATE(), 1, '8:9cbc4255baede959960b43e7b586eeb1', 'addLookupTable existingColumnName=email, existingTableName=authors, newColumnName=authors_email, newTableName=authors_data', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725979910')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO