USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:42.616' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE posts ALTER COLUMN inserted_date date NOT NULL
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/addNotNullConstraint.xml', GETDATE(), 1, '8:2d2a574a8dcf9fd80a010b8cf7e9d6bd', 'addNotNullConstraint columnName=inserted_date, constraintName=test_notNull, tableName=posts', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725983613')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO