USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:48.264' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE authors ADD CONSTRAINT test_unique_constraint UNIQUE (email)
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/addUniqueConstraint.xml', GETDATE(), 1, '8:38f2dfe94a6e9a4be62c5ba628027506', 'addUniqueConstraint constraintName=test_unique_constraint, tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725988874')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO