USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:39:54.411' WHERE ID = 1 AND LOCKED = 0
GO
CREATE NONCLUSTERED INDEX idx_first_name ON authors(first_name)
GO
CREATE NONCLUSTERED INDEX idx_last_name ON authors(last_name)
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3', 'oleh', 'liquibase/harness/change/changelogs/createIndex.xml', GETDATE(), 1, '8:b301ee701bd7d61e0eedf6fed160bde7', 'createIndex indexName=idx_first_name, tableName=authors createIndex indexName=idx_last_name, tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9725995167')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO