USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:12.107' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE lms_create_table_test (lms_test_id int, lms_test_timestamp datetime)
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'okush', 'liquibase/harness/change/changelogs/createTableTimestamp.xml', GETDATE(), 1, '8:6156faebf1e9d0153ed8ff878d60a33f', 'createTable tableName=lms_create_table_test', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726012711')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO