USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:38.793' WHERE ID = 1 AND LOCKED = 0
GO
CREATE SEQUENCE test_sequence START WITH 1 INCREMENT BY 1 MINVALUE 1
GO
DROP SEQUENCE test_sequence
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/mssql/dropSequence.xml', GETDATE(), 1, '8:bc996ea0aa524283e2b5c850b6960da6', 'createSequence sequenceName=test_sequence dropSequence sequenceName=test_sequence', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726039409')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO