USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:32.898' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE posts ADD CONSTRAINT pk_posts PRIMARY KEY (id)
GO
ALTER TABLE posts DROP CONSTRAINT pk_posts
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/dropPrimaryKey.xml', GETDATE(), 1, '8:92cc681a666892c847dba533d13962d3', 'addPrimaryKey constraintName=pk_posts, tableName=posts dropPrimaryKey constraintName=pk_posts, tableName=posts', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726033487')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO