USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:27.221' WHERE ID = 1 AND LOCKED = 0
GO
CREATE NONCLUSTERED INDEX idx_first_name ON authors(first_name)
GO
DROP INDEX idx_first_name ON authors
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3', 'oleh', 'liquibase/harness/change/changelogs/dropIndex.xml', GETDATE(), 1, '8:ef63e81584e5b135ee71b821032facaf', 'createIndex indexName=idx_first_name, tableName=authors dropIndex indexName=idx_first_name, tableName=authors', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726027733')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO