USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:47.34' WHERE ID = 1 AND LOCKED = 0
GO
CREATE VIEW test_view AS select id, first_name, last_name, email from authors
GO
DROP VIEW test_view
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2', 'oleh', 'liquibase/harness/change/changelogs/dropView.xml', GETDATE(), 1, '8:42b034bc536d832e2fd512e915b48e51', 'createView viewName=test_view dropView viewName=test_view', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726047909')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO