USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:41.676' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE test_table (test_id int NOT NULL, test_column varchar(50) NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (test_id))
GO
DROP TABLE test_table
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/dropTable.xml', GETDATE(), 1, '8:a88463469aa9594ab1929ced38cdd525', 'createTable tableName=test_table dropTable tableName=test_table', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726042219')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO