USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:29.796' WHERE ID = 1 AND LOCKED = 0
GO
ALTER TABLE posts ALTER COLUMN inserted_date date NOT NULL
GO
ALTER TABLE posts ALTER COLUMN inserted_date date NULL
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/dropNotNullConstraint.xml', GETDATE(), 1, '8:14e022ee4a6fe8719b07d5f2f73c188e', 'addNotNullConstraint columnName=inserted_date, constraintName=test_notNull, tableName=posts dropNotNullConstraint columnName=inserted_date, tableName=posts', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726030341')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO