USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:35.655' WHERE ID = 1 AND LOCKED = 0
GO
CREATE PROCEDURE test_procedure
AS
GO
DROP PROCEDURE test_procedure
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'as', 'liquibase/harness/change/changelogs/mssql/dropProcedure.xml', GETDATE(), 1, '8:95dbca21ea6dd1f857bab1f36eaba1ce', 'createProcedure procedureName=test_procedure dropProcedure procedureName=test_procedure', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726036370')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO