USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:56.61' WHERE ID = 1 AND LOCKED = 0
GO
CREATE SEQUENCE test_sequence START WITH 1 INCREMENT BY 1 MINVALUE 1
GO
SP_RENAME test_sequence ,test_sequence_rename_test
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'oleh', 'liquibase/harness/change/changelogs/mssql/renameSequence.xml', GETDATE(), 1, '8:7bc82e17eea9a8c5c5a68900b441431a', 'createSequence sequenceName=test_sequence renameSequence newSequenceName=test_sequence_rename_test, oldSequenceName=test_sequence', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726057133')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO