USE lbcat
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '5CD90139BV (192.168.192.1)', LOCKGRANTED = '2021-08-23T16:40:59.322' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE oldnametable (test_id int NOT NULL, test_column varchar(50) NOT NULL, CONSTRAINT PK_OLDNAMETABLE PRIMARY KEY (test_id))
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'r2', 'liquibase/harness/change/changelogs/renameTable.xml', GETDATE(), 1, '8:0c74e61c23a882cf3cef40b22cfe3e3a', 'createTable tableName=oldnametable', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726059889')
GO
exec sp_rename 'oldnametable', 'newnametable'
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2', 'r2', 'liquibase/harness/change/changelogs/renameTable.xml', GETDATE(), 2, '8:3784f70d30252f4d8aa698f8c56e1854', 'renameTable newTableName=newnametable, oldTableName=oldnametable', '', 'EXECUTED', NULL, NULL, '4.4.2', '9726059889')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO