-- Manual cleanup commands for Snowflake test database
-- Run these if tests fail due to existing objects

USE ROLE LIQUIBASE_TEST_HARNESS_ROLE;
USE DATABASE LTHDB;

-- Clean up all test schemas
DROP SCHEMA IF EXISTS TEST_SCHEMA CASCADE;
DROP SCHEMA IF EXISTS SCHEMA_WITH_COMMENT CASCADE;
DROP SCHEMA IF EXISTS TRANSIENT_SCHEMA CASCADE;
DROP SCHEMA IF EXISTS MANAGED_SCHEMA CASCADE;
DROP SCHEMA IF EXISTS RETENTION_SCHEMA CASCADE;
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE;

-- Reset changelog tables
DELETE FROM DATABASECHANGELOG WHERE FILENAME NOT LIKE '%init.xml';
UPDATE DATABASECHANGELOGLOCK SET LOCKED = FALSE WHERE ID = 1;