#release configuration
#Thu Jun 11 13:05:22 UTC 2026
completedPhase=end-release
exec.activateProfiles=github
exec.additionalArguments=-Dmaven.javadoc.skip\=true -Dmaven.test.skipTests\=true -Dmaven.test.skip\=true -Dmaven.deploy.skip\=true
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.liquibase\:liquibase-test-harness=1.1.0-SNAPSHOT
project.rel.org.liquibase\:liquibase-test-harness=1.0.12
project.scm.org.liquibase\:liquibase-test-harness.connection=scm\:git\:https\://github.com/liquibase/liquibase-test-harness.git
project.scm.org.liquibase\:liquibase-test-harness.tag=HEAD
project.scm.org.liquibase\:liquibase-test-harness.url=https\://github.com/liquibase/liquibase-test-harness
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=temp
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/liquibase/liquibase-test-harness.git
