ALTER TABLE "DB2INST1".posts ADD varcharColumn VARCHAR(25)
CALL SYSPROC.ADMIN_CMD ('REORG TABLE "DB2INST1".posts')
UPDATE "DB2INST1".posts SET varcharColumn = 'INITIAL_VALUE'
ALTER TABLE "DB2INST1".posts DROP COLUMN varcharColumn
CALL SYSPROC.ADMIN_CMD ('REORG TABLE "DB2INST1".posts')