CREATE TABLE "DB2INST1".oldnametable (test_id INTEGER NOT NULL, test_column VARCHAR(50) NOT NULL, CONSTRAINT PK_OLDNAMETABLE PRIMARY KEY (test_id))
RENAME "DB2INST1".oldnametable TO newnametable
CALL SYSPROC.ADMIN_CMD ('REORG TABLE "DB2INST1".newnametable')