CREATE TABLE "IBMUSER".authors_data (authors_email VARCHAR(100) NOT NULL)
INSERT INTO "IBMUSER".authors_data SELECT DISTINCT email FROM "IBMUSER".authors WHERE email IS NOT NULL
ALTER TABLE "IBMUSER".authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE "IBMUSER".authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES "IBMUSER".authors_data (authors_email)