-- Snowflake Test Harness Nuclear Cleanup Script
-- This script provides complete schema reset for reliable test isolation
-- Based on proven manual cleanup pattern that eliminates state management issues

-- Use the test harness role and database
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE;
USE DATABASE LTHDB;

-- Nuclear cleanup: Drop and recreate the schema
-- CASCADE ensures ALL objects are removed (tables, views, sequences, procedures, etc.)
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE;
CREATE SCHEMA TESTHARNESS;

-- Restore proper permissions after schema recreation
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE TABLE ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE VIEW ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE FUNCTION ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Grant future object permissions
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Account-level objects (warehouses, databases) are preserved
-- This ensures warehouse tests can create/drop warehouses without interference