INVALID TEST
Ignoring because of liquibase bug, https://github.com/liquibase/liquibase/issues/2863
generated query is incorect
ALTER TABLE PUBLIC.autoincrement_test ALTER COLUMN intColumn int GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 2)
should be
ALTER TABLE PUBLIC.autoincrement_test ALTER COLUMN intColumn int GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 2)
without comma