-- Minimal Snowflake Test Harness Init Script
-- Assumes database, schema, role, and warehouse already exist
-- This just ensures the Liquibase tracking tables are present

-- Use the test database and schema
USE DATABASE LTHDB;
USE SCHEMA TESTHARNESS;
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE;
USE WAREHOUSE LTHDB_TEST_WH;

-- Create Liquibase tracking tables if they don't exist
CREATE TABLE IF NOT EXISTS DATABASECHANGELOG (
    ID VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    DATEEXECUTED TIMESTAMP NOT NULL,
    ORDEREXECUTED INT NOT NULL,
    EXECTYPE VARCHAR(10) NOT NULL,
    MD5SUM VARCHAR(35),
    DESCRIPTION VARCHAR(255),
    COMMENTS VARCHAR(255),
    TAG VARCHAR(255),
    LIQUIBASE VARCHAR(20),
    CONTEXTS VARCHAR(255),
    LABELS VARCHAR(255),
    DEPLOYMENT_ID VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS DATABASECHANGELOGLOCK (
    ID INT NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    LOCKGRANTED TIMESTAMP,
    LOCKEDBY VARCHAR(255),
    PRIMARY KEY (ID)
);

-- Initialize the lock table
MERGE INTO DATABASECHANGELOGLOCK AS target
USING (SELECT 1 AS ID) AS source
ON target.ID = source.ID
WHEN NOT MATCHED THEN
    INSERT (ID, LOCKED) VALUES (1, FALSE)
WHEN MATCHED THEN
    UPDATE SET LOCKED = FALSE;

-- Clean any stale entries from previous runs
DELETE FROM DATABASECHANGELOG WHERE FILENAME NOT LIKE '%init.xml';

-- Ensure the lock is released
UPDATE DATABASECHANGELOGLOCK SET LOCKED = FALSE WHERE ID = 1;