CREATE TABLE LIQUIBASE.authors_data AS SELECT DISTINCT email AS authors_email FROM LIQUIBASE.authors WHERE email IS NOT NULL
ALTER TABLE LIQUIBASE.authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE LIQUIBASE.authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES LIQUIBASE.authors_data (authors_email)