CREATE TABLE "C##LIQUIBASE".authors_data AS SELECT DISTINCT email AS authors_email FROM "C##LIQUIBASE".authors WHERE email IS NOT NULL
ALTER TABLE "C##LIQUIBASE".authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE "C##LIQUIBASE".authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES "C##LIQUIBASE".authors_data (authors_email)