## This configuration was generated by terraform-provider-oci

data "oci_identity_availability_domains" "ads" {
	compartment_id = var.tenancy_ocid
	}

resource oci_database_db_system createdbs {
  availability_domain     = data.oci_identity_availability_domains.ads.availability_domains[0].name
  compartment_id          = var.compartment_ocid
  cpu_core_count          = var.cpu_core_count
  data_storage_percentage = var.data_storage_percentage
  data_storage_size_in_gb = var.data_storage_size_in_gb
  database_edition        = var.database_edition
  db_home {
    database {
      admin_password = var.db_admin_pass
      character_set  = "AL32UTF8"
      db_backup_config {
    	auto_backup_enabled     = "true"
    	auto_backup_window      = "SLOT_TWO"
    	recovery_window_in_days = "7"
      }
      db_name     = "testdb"
      db_workload = "OLTP"
      freeform_tags = {
      }
      ncharacter_set = "AL16UTF16"
      pdb_name       = "pdb1"
    }
    db_version   = var.db_version
    display_name = "testharnessdb"
  }

  db_system_options {
    storage_management = "ASM"
  }
  #
  disk_redundancy = "HIGH"
  display_name    = "Test Harness DB"
  #domain          = "privatesubnet.vcn.oraclevcn.com"
  hostname      = var.db_hostname
  license_model = var.license_model
  node_count    = var.node_count
  shape         = var.shape
  source        = "NONE"
  ssh_public_keys = [var.ssh_public_key,]
  subnet_id = var.subnet_id
  time_zone = var.time_zone
  timeouts {
    create = "3h"
    delete = "2h"
  }
}

output "dbs_details" {
   value = oci_database_db_system.createdbs
}
