CREATE TABLE TEST_TABLE_BASE (ID NUMBER(*, 0) NOT NULL, CONSTRAINT PK_TEST_TABLE_BASE PRIMARY KEY (ID));

CREATE TABLE TEST_TABLE_REFERENCE (ID NUMBER(*, 0) NOT NULL, TEST_COLUMN NUMBER(*, 0), CONSTRAINT PK_TEST_TABLE_REFERENCE PRIMARY KEY (ID));

ALTER TABLE TEST_TABLE_BASE ADD CONSTRAINT TEST_FK FOREIGN KEY (ID) REFERENCES TEST_TABLE_REFERENCE (ID) ON DELETE CASCADE;

