CREATE TABLE TEST_TABLE_BASE (ID INT NOT NULL, CONSTRAINT PK_TEST_TABLE_BASE PRIMARY KEY (ID));

CREATE TABLE TEST_TABLE_REFERENCE (ID INT NOT NULL, TEST_COLUMN INT NOT NULL, CONSTRAINT PK_TEST_TABLE_REFERENCE PRIMARY KEY (ID));

ALTER TABLE TEST_TABLE_REFERENCE ADD CONSTRAINT TEST_TABLE_REFERENCE_UNIQUE UNIQUE (TEST_COLUMN);

ALTER TABLE TEST_TABLE_BASE ADD CONSTRAINT TEST_FK FOREIGN KEY (ID) REFERENCES TEST_TABLE_REFERENCE (TEST_COLUMN) ON UPDATE NO ACTION ON DELETE CASCADE;