CREATE TABLE TEST_TABLE (ID NUMBER(*, 0));

CREATE INDEX TEST_UNIQUE_CONSTRAINT ON TEST_TABLE(ID);

ALTER TABLE TEST_TABLE ADD CONSTRAINT TEST_UNIQUE_CONSTRAINT UNIQUE (ID) USING INDEX TEST_UNIQUE_CONSTRAINT;