name: 'Get Stack ID'
description: 'Get stack ID from deploy-ephemeral-cloud-infra job output without triggering secret masking'
inputs:
  stack-id:
    description: 'Stack ID from deploy-ephemeral-cloud-infra job'
    required: true
  run-id:
    description: 'GitHub run ID for generating stack name'
    required: false
    default: ${{ github.run_id }}
outputs:
  stack-id:
    description: 'Processed stack ID'
    value: ${{ steps.process-stack-id.outputs.stack-id }}
runs:
  using: 'composite'
  steps:
    - name: Process stack ID
      id: process-stack-id
      shell: bash
      run: |
        # Process the stack ID to avoid secret masking
        INPUT_STACK_ID="${{ inputs.stack-id }}"
        
        # Check if the input is masked (contains ***)
        if [[ "$INPUT_STACK_ID" == *"***"* ]]; then
          echo "Stack ID is masked, reconstructing from run ID..."
          # Reconstruct the stack ID using the known pattern
          # Pattern: liquibase-test-automation-ephemeral-{run_id}
          RECONSTRUCTED_ID="liquibase-test-automation-ephemeral-${{ inputs.run-id }}"
          echo "stack-id=$RECONSTRUCTED_ID" >> $GITHUB_OUTPUT
          echo "Reconstructed stack ID: $RECONSTRUCTED_ID"
        else
          echo "Stack ID is not masked, using as-is..."
          echo "stack-id=$INPUT_STACK_ID" >> $GITHUB_OUTPUT
          echo "Using stack ID: $INPUT_STACK_ID"
        fi