CREATE TABLE DATICAL_ADMIN.authors_data AS SELECT DISTINCT email AS authors_email FROM DATICAL_ADMIN.authors WHERE email IS NOT NULL
ALTER TABLE DATICAL_ADMIN.authors_data ADD PRIMARY KEY (authors_email)
ALTER TABLE DATICAL_ADMIN.authors ADD CONSTRAINT FK_AUTHORS_AUTHORS_DATA FOREIGN KEY (email) REFERENCES DATICAL_ADMIN.authors_data (authors_email)