CREATE TABLE TEST_TABLE (ID NUMBER(*, 0));

CREATE INDEX TEST_UNIQUE_CONSTRAINT ON TEST_TABLE(ID);

ALTER TABLE TEST_TABLE ADD CONSTRAINT TEST_UNIQUE_CONSTRAINT UNIQUE (ID) USING INDEX TEST_UNIQUE_CONSTRAINT;

CREATE PUBLIC SYNONYM "AWS$ARN" FOR "AWS$ARN";

CREATE PUBLIC SYNONYM "AZURE$PA" FOR "AZURE$PA";

CREATE PUBLIC SYNONYM "GCP$PA" FOR "GCP$PA";

CREATE PUBLIC SYNONYM "OCI$RESOURCE_PRINCIPAL" FOR "OCI$RESOURCE_PRINCIPAL";