CREATE TABLE TEST_TABLE (TEST_COLUMN NUMBER(*, 0), VARCHARCOLUMN VARCHAR2(25 BYTE), INTCOLUMN NUMBER(*, 0), DATECOLUMN date);

CREATE PUBLIC SYNONYM "AWS$ARN" FOR "AWS$ARN";

CREATE PUBLIC SYNONYM "AZURE$PA" FOR "AZURE$PA";

CREATE PUBLIC SYNONYM "GCP$PA" FOR "GCP$PA";

CREATE PUBLIC SYNONYM "OCI$RESOURCE_PRINCIPAL" FOR "OCI$RESOURCE_PRINCIPAL";