CREATE TABLE TEST_TABLE (ID INTEGER NOT NULL, TEST_COLUMN VARCHAR(100) NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (ID));

ALTER TABLE TEST_TABLE ADD CONSTRAINT SOME_CONST UNIQUE (TEST_COLUMN);

CREATE INDEX TEST_TABLE_INDEX ON TEST_TABLE(TEST_COLUMN);