name: Release Test-Harness
on:
  workflow_dispatch:
    inputs:
      extensionVersion:
        description: 'Extension Version to release'
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      extensionVersion: ${{ steps.collect-data.outputs.extensionVersion }}
    steps:
      - name: Collect Data
        id: collect-data
        uses: actions/github-script@v6.1.1
        with:
          script: |
            if (context.payload.inputs) {
                core.setOutput("extensionVersion", context.payload.inputs.extensionVersion);
            } else {
              core.setFailed('Unknown event type')
            }

      - run: |
          echo "Saw Extension to release version ${{ steps.collect-data.outputs.extensionVersion }}"

  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      releaseSha: ${{ steps.get-release-sha.outputs.releaseSha }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Cache Built Code
        uses: actions/cache@v3
        with:
          key: built-code-${{ github.run_id }}
          path: ./**/target

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure git user
        run: |
          git config user.name "liquibot"
          git config user.email "liquibot@liquibase.org"

      - name: Update pom.xml with release versions and commit changes
        run: |
          mvn -B versions:set -DnewVersion=${{ needs.setup.outputs.extensionVersion }} -DallowSnapshots=false -DoldVersion="*"          

          git add pom.xml
          if git diff-index --cached --quiet HEAD --
          then
            echo "Nothing new to commit"
          else
            git commit -m "Version Bumped to ${{ needs.setup.outputs.extensionVersion }}"
          fi
          git tag -a -m "Version Bumped to ${{ needs.setup.outputs.extensionVersion }}" liquibase-test-harness-${{ needs.setup.outputs.extensionVersion }}
          git push "https://liquibot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.ref }} --follow-tags --tags

        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Get release SHA
        id: get-release-sha
        run: echo ::set-output name=releaseSha::$(git rev-parse HEAD)


      - name: Build and Unit Test
        run: mvn -B clean -Dmaven.test.skip package

      - name: Archive Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-jdk
          path: ./**/target/surefire-reports

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: liquibase-test-harness
          path: |
            target/*.jar


  draft-release:
    needs: [ setup, build ]
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: liquibase-test-harness

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          target_commitish: ${{ needs.build.outputs.releaseSha }}
          name: v${{ needs.setup.outputs.extensionVersion }}
          tag_name: liquibase-test-harness-${{ needs.setup.outputs.extensionVersion }}
          draft: true
          body: In version ${{ needs.setup.outputs.extensionVersion }} we
          files: liquibase-test-harness-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-pom-to-snapshot:
    name: Prepare POM for Development
    runs-on: ubuntu-latest
    needs: [ draft-release ]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure git user
        run: |
          git config user.name "liquibot"
          git config user.email "liquibot@liquibase.org"

      - name: Prepare code for next version
        run: |
          git pull
          mvn -B versions:set -DnextSnapshot=true
          git add pom.xml
          git commit -m "Version Bumped to Snapshot for Development"
          git push "https://liquibot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.ref }} --follow-tags --tags
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
