name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@main
    secrets: inherit
    with:
      sonar: false
