name: Deploy Main Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write 
  id-token: write

jobs:
  extension-deploy-main-snapshot:
    uses: liquibase/build-logic/.github/workflows/build-extension-jar.yml@main
    secrets: inherit
    with:
      extension: liquibase-test-harness
      groupId: org.liquibase
