name: Deploy Master Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  extension-deploy-master-snapshot:
    uses: liquibase/build-logic/.github/workflows/build-extension-jar.yml@main
    secrets: inherit
    with:
      extension: liquibase-test-harness
      groupId: org.liquibase
