name: Deploy Master Snapshot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
          server-id: github
          server-username: liquibot
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version to master-SNAPSHOT
        run: mvn versions:set -DnewVersion=master-SNAPSHOT

      - name: Build and deploy snapshot
        run: mvn deploy -P release -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
