# Terraform Action to test Cloud Databases with test-harness

name: Google Cloud Database Test Execution
concurrency: gcp-run
on:
  # Triggers the workflow on a schedule for the main branch. Also allows for manual triggers
  schedule:
    - cron: "0 5 * * *" # Execute every day at 5AM UTC
  workflow_dispatch:
    inputs:
      testClasses:
        type: choice
        description: Test Suite or test class to run
        options:
          - AdvancedHarnessSuiteTest
          - LiquibaseHarnessSuiteTest
          - FoundationalHarnessSuiteTest
          - ChangeObjectTests
          - ChangeDataTests
          - SnapshotObjectTests
          - GenerateChangelogTest
          - FoundationalTest
      databases:
        description: Databases to start up. Comma separated list of "name:version"
        required: true
        default: '["postgresql:12","postgresql:13","postgresql:14","postgresql:15","mysql:gcp","mssql:gcp_2019","mssql:gcp_2022"]'

permissions:
  contents: write
  id-token: write
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      databases: ${{ github.event.inputs.databases || '["postgresql:12","postgresql:13","postgresql:14","postgresql:15","mysql:gcp","mssql:gcp_2019","mssql:gcp_2022"]' }}
      testClasses: ${{ inputs.testClasses  || 'LiquibaseHarnessSuiteTest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  init-mysql:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - database: mysql
            version: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      #      This additional init step is required because of mysql driver issue on GH actions
      - name: Install Dependencies
        run: lpm update && lpm add mysql

      - name: Clean GCP MySQL Database
        uses: liquibase-github-actions/drop-all@v4.32.0
        if: ${{ matrix.database == 'mysql' }}
        with:
          url: "${{ env.TH_GCP_MYSQL_8_0_URL }}"
          username: "${{env.TH_DB_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          licenseKey: "${{env.PRO_LICENSE_KEY}}"
          force: true
          requireForce: true

      - name: Init Database
        if: ${{ matrix.database == 'mysql' }}
        run: liquibase --classpath="src/test/resources/init-changelogs/gcp" --changeLogFile="${{ matrix.database }}.sql" --username="${{ env.TH_DB_ADMIN }}" --password="${{ env.TH_DB_PASSWD }}" --url="${{ env.TH_GCP_MYSQL_8_0_URL }}" update

  test:
    needs: [init-mysql, setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJson(needs.setup.outputs.databases) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true
          
      - name: Configure Test
        id: setup
        uses: actions/github-script@v7.0.1
        with:
          script: |
            let splitValues = "${{ matrix.database }}".split(":")
            core.setOutput("databasePlatform", splitValues[0]);
            core.setOutput("databaseVersion", splitValues[1]);

      - uses: liquibase-github-actions/drop-all@v4.32.0
        if: ${{ steps.setup.outputs.databasePlatform == 'postgresql' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          url: "${{ env[format('TH_GCP_POSTGRESQL_{0}_URL', steps.setup.outputs.databaseVersion)] }}"
          username: "${{env.TH_DB_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          licenseKey: "${{env.PRO_LICENSE_KEY}}"
          force: true
          requireForce: true

      - uses: liquibase/liquibase-github-action@v7
        if: ${{ steps.setup.outputs.databasePlatform == 'postgresql' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          operation: "update"
          classpath: "src/test/resources/init-changelogs/aws"
          changeLogFile: "postgresql.sql"
          username: "${{env.TH_DB_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          url: "${{ env[format('TH_GCP_POSTGRESQL_{0}_URL', steps.setup.outputs.databaseVersion)] }}"

      - uses: liquibase-github-actions/drop-all@v4.32.0
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2019' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          url: "${{ env.TH_GCP_MSSQL_2019_URL }}"
          username: "${{env.MSSQL_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          licenseKey: "${{env.PRO_LICENSE_KEY}}"
          force: true
          requireForce: true

      - uses: liquibase-github-actions/drop-all@v4.32.0
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2022' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          url: "${{ env.TH_GCP_MSSQL_2022_URL }}"
          username: "${{env.MSSQL_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          licenseKey: "${{env.PRO_LICENSE_KEY}}"
          force: true
          requireForce: true

      - uses: liquibase/liquibase-github-action@v7
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2019' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          operation: "update"
          classpath: "src/test/resources/init-changelogs/gcp"
          changeLogFile: "mssql.sql"
          username: "${{env.MSSQL_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          url: "${{ env.TH_GCP_MSSQL_2019_URL }}"

      - uses: liquibase/liquibase-github-action@v7
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2022' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        with:
          operation: "update"
          classpath: "src/test/resources/init-changelogs/gcp"
          changeLogFile: "mssql.sql"
          username: "${{env.MSSQL_ADMIN}}"
          password: "${{env.TH_DB_PASSWD}}"
          url: "${{ env.TH_GCP_MSSQL_2022_URL }}"

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: GCP ${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }} Test Run
        if: ${{ steps.setup.outputs.databasePlatform == 'postgresql' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        run: mvn -Dtest=${{ needs.setup.outputs.testClasses }} -DconfigFile=/harness-config-cloud.yml -DdbName=${{ steps.setup.outputs.databasePlatform }} -DdbVersion=${{ steps.setup.outputs.databaseVersion }} -Dprefix=gcp -DdbUsername=${{env.TH_DB_ADMIN}} -DdbPassword=${{env.TH_DB_PASSWD}} -DdbUrl='${{ env[format('TH_GCP_POSTGRESQL_{0}_URL', steps.setup.outputs.databaseVersion)] }}' test

      - name: GCP ${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }} Test Run
        if: ${{ steps.setup.outputs.databasePlatform == 'mysql' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
        run: mvn -Dtest=${{ needs.setup.outputs.testClasses }} -DconfigFile=/harness-config-cloud.yml -DdbName=${{ steps.setup.outputs.databasePlatform }} -DdbVersion=${{ steps.setup.outputs.databaseVersion }} -DdbUsername=${{env.TH_DB_ADMIN}} -DdbPassword=${{env.TH_DB_PASSWD}} -DdbUrl='${{ env.TH_GCP_MYSQL_8_0_URL }}' test

      - name: GCP ${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }} Test Run
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2019' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
          LIQUIBASE_LIQUIBASE_SCHEMA_NAME: lbuser
        run: mvn -Dtest=${{ needs.setup.outputs.testClasses }} -DconfigFile=/harness-config-cloud.yml -DdbName=${{ steps.setup.outputs.databasePlatform }} -DdbVersion=gcp -Dprefix=gcp -DdbUsername=${{env.TH_DB_ADMIN}} -DdbPassword=${{env.TH_DB_PASSWD}} -DdbUrl='${{ env.TH_GCP_MSSQL_2019_URL }}' test

      - name: GCP ${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }} Test Run
        if: ${{ steps.setup.outputs.databasePlatform == 'mssql' && steps.setup.outputs.databaseVersion == 'gcp_2022' }}
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ env.PRO_LICENSE_KEY }}
          LIQUIBASE_LIQUIBASE_SCHEMA_NAME: lbuser
        run: mvn -Dtest=${{ needs.setup.outputs.testClasses }} -DconfigFile=/harness-config-cloud.yml -DdbName=${{ steps.setup.outputs.databasePlatform }} -DdbVersion=gcp -Dprefix=gcp -DdbUsername=${{env.TH_DB_ADMIN}} -DdbPassword=${{env.TH_DB_PASSWD}} -DdbUrl='${{ env.TH_GCP_MSSQL_2022_URL }}' test

      - name: Archive GCP ${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }} Test Results
        uses: actions/upload-artifact@v4
        with:
          name: gcp-${{ steps.setup.outputs.databasePlatform }}-${{ steps.setup.outputs.databaseVersion }}-test-results
          path: build/spock-reports
