# Basic workflow with Actions

name: Oracle Test Execution
on:

  # schedule:
  #  - cron: '0 8 * * *' # Execute every day at 8am
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'


      - name: Docker login to retrive Oracle images from private repo
        run: docker login "${{ secrets.ARTIFACTORY_URL }}" -u "${{ secrets.ARTIFACTORY_USER }}" -p "${{ secrets.ARTIFACTORY_TOKEN }}"

      - name: Build Oracle Artifactory test infra
        working-directory: src/test/resources/docker/oracle-artifactory
        run: docker-compose up -d

      - name: Build Oracle XE test infra
        working-directory: src/test/resources/docker/oracle-xe
        run: docker-compose up -d

# Adding sleep to avoid ORA-12514 error when database & listeners are still in the middle of startup
      - name: Sleep for 180 seconds
        uses: whatnick/wait-action@master
        with:
          time: '180s'

      - name: Oracle Test Run
        run: mvn -Dtest=LiquibaseHarnessSuiteTest -DdbName=oracle -DdbVersion=18.3.0 test
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LICENSE_KEY }}

      - name: Archive oracle test results
        uses: actions/upload-artifact@v2
        with:
          name: oracle-test-results
          path: build/spock-reports

      - name: Tear down oracle test infra
        working-directory: src/test/resources/docker/oracle-artifactory
        run: docker-compose down --volumes


      - name: Oracle XE Test Run
        run: mvn -Dtest=LiquibaseHarnessSuiteTest -DdbName=oracle -DdbVersion=18.4.0 test
        env:
          LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LICENSE_KEY }}

      - name: Archive oracle test results
        uses: actions/upload-artifact@v2
        with:
          name: oracle-xe-test-results
          path: build/spock-reports

      - name: Tear down oracle XE test infra
        working-directory: src/test/resources/docker/oracle-xe
        run: docker-compose down --volumes
