# Basic workflow with Actions

name: Test Execution
on:

  schedule:
    - cron: '0 8 * * *' # Execute every day at 8am
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'


      - name: Docker login to retrive Oracle images from private repo
        run: docker login "${{ secrets.RT_URL }}" -u "${{ secrets.RT_USER }}" -p "${{ secrets.RT_PWD }}"

      - name: Build Oracle test infra
        working-directory: src/test/resources/docker/oracle-artifactory
        run: docker-compose up -d

      - name: Oracle Test Run
        run: mvn -Dtest=LiquibaseHarnessSuiteTest -DdbName=oracle -DdbVersion=12.2.0.1 test

      - name: Archive oracle test results
        uses: actions/upload-artifact@v2
        with:
          name: oracle-test-results
          path: build/spock-reports

      - name: Tear down oracle test infra
        working-directory: src/test/resources/docker/oracle-artifactory
        run: docker-compose down --volumes