# Basic workflow with Actions

name: Default Test Execution
on:
  # Triggers the workflow on push & pull request events for the main branch. Also allows for manual triggers
  push:
    branches: [ feature/cicd-titan ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Execute every day at noon
  workflow_dispatch:


jobs:
  diff:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'

      - name: Build Diff test infra
        working-directory: src/test/resources/docker
        run: docker compose up -d postgres-9 postgres-12 mysql-5.7 mysql-8

      - name: Diff Test Run
        run: mvn -Dtest=DiffTest test

      - name: Archive Diff test results
        uses: actions/upload-artifact@v2
        with:
          name: diff-test-results
          path: build/spock-reports

      # GitHub Actions has its own cleanup and this might be redundant
      - name: Tear down Diff test infra
        working-directory: src/test/resources/docker
        run: docker compose down --volumes

  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        database: [
            "mysql-5.6",
            "mysql-5.7",
            "mysql-8",
            "postgres-9.5",
            "postgres-9",
            "postgres-10",
            "postgres-11",
            "postgres-12",
            "postgres-13",
            "mariadb-10.3",
            "mariadb-10.5",
            "mssql-2017",
            "mssql-2019",
            "H2Database-1.4",
            "crdb-20.2",
            "crdb-20.1",
            "crdb-21.1",
            "edb-9.5",
            "edb-9.6",
            "edb-10",
            "edb-11",
            "edb-12",
            "edb-13"
        ]
        #SQLite
        #Derby

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'

      - name: Build ${{ matrix.database }} test infra
        working-directory: src/test/resources/docker
        run: ./create-infra.sh ${{ matrix.database }}
        env:
          RT_URL: ${{ secrets.RT_URL }}
          RT_USER: ${{ secrets.RT_USER }}
          RT_PWD: ${{ secrets.RT_PWD }}

      - name: ${{ matrix.database }} Test Run
        run: ./src/test/resources/automation-runner.sh ${{ matrix.database }}

      - name: Archive ${{ matrix.database }} test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.database }}-test-results
          path: build/spock-reports

      # GitHub Actions has its own cleanup and this might be redundant
      - name: Tear down ${{ matrix.database }} test infra
        working-directory: src/test/resources/docker
        run: ./teardown-infra.sh ${{ matrix.database }}