# Basic workflow with Actions

name: Default Test Execution
on:
  # Triggers the workflow on push & pull request events for the main branch. Also allows for manual triggers
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Execute every day at noon
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        database: [ "mysql-5.6", "mysql-8", "postgres-12", "edb-13" ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'

      - name: Build ${{ matrix.database }} test infra
        working-directory: src/test/resources/docker
        run: ./create-infra.sh ${{ matrix.database }}
        env:
          RT_URL: ${{ secrets.RT_URL }}
          RT_USER: ${{ secrets.RT_USER }}
          RT_PWD: ${{ secrets.RT_PWD }}

      - name: ${{ matrix.database }} Test Run
        run: ./src/test/resources/automation-runner.sh ${{ matrix.database }}

      - name: Archive ${{ matrix.database }} test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.database }}-test-results
          path: build/spock-reports

      # GitHub Actions has its own cleanup and this might be redundant
      - name: Tear down ${{ matrix.database }} test infra
        working-directory: src/test/resources/docker
        run: ./teardown-infra.sh ${{ matrix.database }}